# Generated by Django 4.0.4 on 2022-05-10 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, max_length=80, null=True)),
                ('desc', models.TextField(blank=True, max_length=50, null=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/image')),
                ('our_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
