# Generated by Django 4.0.4 on 2022-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='upload',
            field=models.ImageField(upload_to='uploads/image'),
        ),
    ]
