# Generated by Django 4.0.4 on 2022-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image'),
        ),
    ]
